// Various measurements in pixels
export const TILE_HEIGHT = 8;
export const TILE_WIDTH = 8;
export const FONT_CHARACTER_WIDTH = TILE_WIDTH;
export const FONT_CHARACTER_HEIGHT = TILE_HEIGHT;
export const DIALOG_WINDOW_WIDTH = 160;
export const DIALOG_WINDOW_HEIGHT = 40;
export const PORTRAIT_WIDTH = 32;
export const PORTRAIT_HEIGHT = 32;